#!/bin/bash

count_normal=-1

while IFS= read -r line; do
    if [[ $line == "linux" ]]; then
        count_kernel=1
    else
        count_normal=$((count_normal + 1))
    fi
done <<< "$(checkupdates)"

if [[ $count_normal == 0 ]]; then
    exit
elif [[ $count_kernel ==  1 ]]; then
    echo "Updates: $count_normal + kernel"
else
    echo "Updates: $count_normal"
fi
