#!/bin/bash

if [ -n "$(df | ag $1)" ]; then
    total=$(df -h --output=pcent $1 | tail -n1 | sed 's/ //g' | sed 's/%//')
    space=$(df -h --output=avail $1 | tail -n1 | sed 's/ //g')

    echo $space
    echo $space

    awk -v total=$total '
        BEGIN {
            if (total >= 90) {
                print "#FF0000";
            }
            else if (total >= 70) {
                print "#FFA500";
            }
        }
    '
else
    echo "-"
fi


