#!/bin/bash

task_file="$HOME/.i3/i3blocktask"

# Check if the file is empty
# if so, we are starting for the first time,
# so don't show the rofi dialoge
if [ ! -s "$task_file" ]; then
    name="$(task minimal | \
        head -n 4 | \
        tail -n 1 | \
        cut -d ' ' -f3-)"
    echo "$name" > "$task_file"
    echo "$name"
    exit
fi

# What we want to show in the i3bar
to_show="$(task minimal | \
            head -n -2 | \
            tail -n +4 | \
            rofi -dmenu -separator-style "none" -hide-scrollbar -width 20 -m 0 -p "task:" )"

# Remove the leading whitespace
to_show="${to_show## }"

# If we didn't select anything, just show what's in the file
if [ -z "$to_show" ]; then
    # Cut the number, so we only get the actual task
    cut -d ' ' -f2- "$task_file"
else
    echo "$to_show" | cut -d ' ' -f2-
    echo "$to_show" > "$task_file"
fi


