#!/bin/bash

count_normal=-1

while IFS="\n" read -r line; do
    if [[ $line == "linux" ]]; then
        count_kernel=1
    fi
    count_normal=$((count_normal + 1))
done <<< "$(checkupdates)"

if [[ $count_normal == 0 ]]; then
    exit
elif [[ $count_kernel ==  1 ]]; then
    echo "$count_normal + kernel"
else
    echo "$count_normal"
fi
